### ISSUE TITLE
Responsividade com no mobile

### ISSUE THREAD

**Issue by humrochagf** [leportella/leportella.github.io#2]
No mobile fica um espaço em branco por conta dos 20% de margem

Pra remover este espaço basta usar a media tag de tamanho de tela a div home por exemplo ficaria assim:

```css
@media screen and (min-width: 768px) {
  #home {
    margin: 0;
  }
}
```
**Obs.:** 768px é meio que um padrão de que abaixo disso é resolução de celular

Lembrando que por conta do efeito cascata do CSS você precisa adicionar esta regra após a regra que define 20% de margem.
